version: '3.6'

services:
  jonkkins-login:
    build: modules/login
    restart: unless-stopped
    ports:
      - 999:80
    volumes:
      - ./modules/login/src:/app
  front:
    build: front
    ports:
      - 998:80
    volumes:
      - ./front/error:/home/error
      - ./front/pages:/home/pages
  db-api:
    build: modules/db-api
    ports:
      - 1000:80
    volumes:
      - ./modules/db-api/php/apache/sites-available:/etc/apache2/sites-available
      - ./modules/db-api/src:/var/www/html
#    command:
#      - /init.sh
  nosql:
    image: 'mongo:4.2.3-bionic'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_rootpw
      - MONGO_INITDB_ROOT_USERNAME=root
    volumes:
      - './docker/mongo/secrets:/run/secrets'
  nosql-express:
    image: mongo-express
    ports:
      - 9999:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=dddd
      - ME_CONFIG_BASICAUTH_PASSWORD=vvvv
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dddd
      - ME_CONFIG_MONGODB_SERVER=nosql
  db:
    image: 'postgres:9.6.16-alpine'
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      # Please create postgres-passwd file in postgresql/secrets, and put the password here
      - ./docker/postgresql/secrets:/run/secrets
      - ./docker/postgresql/docker-entrypoint-initdb:/docker-entrypoint-initdb.d