version: '3.6'

services:
  jonkkins-login:
    build: modules/login
    ports:
      - 999:80
    volumes:
      - ./modules/login/src:/app
  front:
    build: front
    ports:
      - 998:80
    volumes:
      - ./front/error:/home/error
      - ./front/pages:/home/pages
